# Generated by Django 4.0.6 on 2022-07-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketingapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biz_kimmiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='images/')),
                ('name', models.CharField(max_length=100)),
                ('jobs', models.CharField(max_length=100)),
                ('informations', models.TextField()),
            ],
        ),
    ]
