# Generated by Django 4.0.6 on 2022-07-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketingapp', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slaidshow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='images/')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
